### ISSUE TITLE
ZFS DKMS fails to build on CentOS 8 4.18.0-305.3.1 (NR_SLAB_RECLAIMABLE does not exist)

### ISSUE THREAD

**Issue by arcasinky** [openzfs/zfs#12198]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| 8
Linux Kernel	| 4.18.0-305.3.1.el8.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.2-1
SPL Version	| 0.8.2-1

### Describe the problem you're observing
After a routine kernel update from 4.18.0-240.22.1.el8_3.x86_64 to 4.18.0-305.3.1.el8.x86_64, zfs DKMS fails to build.

```
configure:33288: checking global_page_state enums are sane
configure:33421: result: no
configure:33423: result: NR_SLAB_RECLAIMABLE in either node_stat_item or zone_stat_item: NOT FOUND
configure:33425: result: configure needs updating, see: config/kernel-global_page_state.m4
configure:33427: error: in `/var/lib/dkms/zfs/0.8.2/build':
configure:33429: error: SHUT 'ER DOWN CLANCY, SHE'S PUMPIN' MUD!
See `config.log' for more details
```

Looking at include/linux/mmzone.h, it appears that NR_SLAB_RECLAIMABLE no longer exists in this kernel.  It has been replaced by NR_SLAB_RECLAIMABLE_B:

```
/lib/modules/4.18.0-305.3.1.el8.x86_64/build/include/linux# grep -r NR_SLAB_RECLAIMABLE
mmzone.h:	NR_SLAB_RECLAIMABLE_B,
mmzone.h:	return (idx == NR_SLAB_RECLAIMABLE_B ||
```

### Describe how to reproduce the problem
Perform dnf update to install latest kernel.  DKMS fails.

### Include any warning/errors/backtraces from the system logs

See above.

**Comment by rincebrain** [comment]
Oh boy, Redhat backported changes from 5.9.

This was fixed in master in 3e29e197; if you want to keep running 0.8.X for whatever reason, you could try grabbing [the not-released 0.8.7-staging branch](https://github.com/openzfs/zfs/tree/zfs-0.8.7-staging); alternately, any 2.X release from 2.0.3 on will probably work.

**Comment by arcasinky** [comment]
Thanks for the quick response.

No.  This is plain CentOS 8.  I haven't decided whether to update this server to Stream or choose a different distribution.

For what it's worth, I just did a dnf update on a bonafide RHEL 8 system and it also installed 4.18.0-305.  Unsurprisingly, it also is missing NR_SLAB_RECLAIMABLE.  That machine doesn't use ZFS but I have no reason to suspect 0.8.2 would build successfully over there there giving the missing enum.

Thanks for the info about 0.8.7 and 2.X.  Unfortunately neither appear to be available from the zfs repository.  Normally I wouldn't be opposed to building from a git repo but this is a production machine.  I'd like to avoid creating a dependency on manually-built kernel modules.

**Comment by rincebrain** [comment]
Huh, I guess whichever Centos mirror mine picked is slightly out of date. (RHEL having it already doesn't surprise me.)

If you don't want to build from a git repo, you could use the release tarball of 2.0.4.

If you want something prebuilt for that purpose, I believe the "zfs-testing" repo has prebuilt 2.0.X packages on RPM distros.

**Comment by arcasinky** [comment]
Your comment and a couple other comments I read earlier today about the 'zfs' repo requiring point-release updates on made me look more closely at how the zfs repo was configured on this machine...

This system is, indeed, up-to-date meaning that it's currently at CentOS 8.4 according to /etc/centos-release (though, annoyingly, /etc/os-release still shows VERSION_ID="8" ... this is in contrast with an up-to-date RHEL8 system which shows VERSION_ID="8.4").  But the 'zfs-release-xxxx.rpm' package was installed when the machine was still at the CentOS/RHEL 8.0 level.  This explains why I was stuck at the zfs 0.8.2 level.

The most recent available zfs-release-xxxx.rpm package available from EPEL is 8.3 (though, once installed, it reports itself as zfs-release-1-10.noarch) so I installed that.  That gave me access to zfs 0.8.6-level packages.  These do appear to take into account the NR_SLAB_RECLAIMABLE kernel change and so they build and install correctly on kernel 4.18.0-305.3.1. 

So this build problem was my fault for not keeping the installed zfs-release package in sync with the underlying CentOS level.

I think we can close this bug but can we maybe add a warning to "https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html" that the onus is on the user to keep the zfs-release package in-sync with the underlying OS?

**Comment by rincebrain** [comment]
Huh, my bad, I misread where d2acd3696fd4c99f8366b548026c27a3c6c0acaf said what branches it's in, or I would have just told you to try 0.8.6. Sorry for the noise.

Would something like s/Only the current repository for each major release is updated with new packages/Only the current repository for each major release is updated with new packages - **if you do not update the repo file on upgrading point release, you will cease receiving updates**/ work, do you think?

(I would speculate, for people who wanted to stay up to date, the repo could be updated to allow this, then a repo RPM could be provided that just used $releasever instead of hardcoding a version...)

**Comment by arcasinky** [comment]
No worries.  I learned something today.

How about this:  "The kernel's ABI evolves over time.  If you do not update the repo file on upgrading OS point release, you'll cease receiving zfs updates and your installed zfs packages might not work with future kernels.  This means that future kernel updates may cause zfs DKMS build failures (if you're using DKMS) or may cause your zfs kernel modules to fail to load (if you're using the kABI-tracking version)."

**Comment by rincebrain** [comment]
The kmod section has an explicit warning about this, in fact. A complimentary one could be added to the DKMS section, presumably, but my main thought was trying to get people's attention for those who don't realize they need to keep the repo package updated from the note in the initial section.

**Comment by x3nb63** [comment]
> This system is, indeed, up-to-date meaning that it's currently at CentOS 8.4 according to /etc/centos-release (though, annoyingly, /etc/os-release still shows VERSION_ID="8" ... this is in contrast with an up-to-date RHEL8 system which shows VERSION_ID="8.4"). But the 'zfs-release-xxxx.rpm' package was installed when the machine was still at the CentOS/RHEL 8.0 level. This explains why I was stuck at the zfs 0.8.2 level.

any idea on why that VERSION_ID is not updated?

I just stepped right into this by `dnf upgrade`ing a machine and it got a new `/etc/os-release` from `centos-linux-release-8.4-1.2105.el8.noarch` - but still: VERSION_ID="8" in it.

So I don't see how to actually ensure `zfs-release` package matches other than parsing `/etc/centos-release`. The [install procedure for RHEL/CentOS 8 and newer](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL-based%20distro/index.html) leads to failure.

_(I have more machines to do, so want to ansible it ...)_

**Comment by rincebrain** [comment]
I shook this monstrosity out of someone else's answer online, beaten into shape for EL8, tried only on CentOS 8.4:

`VER=$(rpm -qa --qf '%{VERSION}' '(redhat|sl|slf|centos|oraclelinux)(|-linux)-release(|-server|-workstation|-client|-computenode)' | sed -e 's/$/\n/g')`

Feel free to experiment and report back.

**Comment by x3nb63** [comment]
thanks, I did a shorter version cause there is only CentOS here:

`VERSION_ID=$(sed -e 's/.*\s\([0-9]\.[0-9]\)\.[0-9]\{1,4\}$/\1/' /etc/centos-release)`

still don't see why the `centos-linux-release-8.4-1.2105.el8.noarch` package does not upgrade `/etc/os-release` properly - thats a upstream bug, cause "VERSION_ID=8" is not running anymore.

**Comment by arcasinky** [comment]
CentOS Stream 8 appears to have resolved that inconsistency...

```
> rpm -qa | sort | grep -i centos-.*-release
centos-stream-release-8.5-3.el8.noarch

> cat /etc/centos-release 
CentOS Stream release 8

> cat /etc/os-release | grep VERSION_ID
VERSION_ID="8"
```

I suppose the CentOS guys would argue that minor version numbers don't make sense for rolling releases like Stream though I can imagine that'll lead to confusion about what's actually running.

**Comment by x3nb63** [comment]
then the counter-argument would be: why do they have a minor version if it does not make sense? They say stream is 8.5.

looking at this os-release file, given as it is, I expect the sense in having one variable pointing to the major and then another being more specific. So a `VERSION=8` together with `VERSION_ID=8.4` I would actually understand. But ...

```
$ grep VERSION /etc/os-release 
VERSION="8"
VERSION_ID="8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```
I dont know what the condition for increasing that minor number is?

... so I still don't see how to script this properly; my version above wont work on stream,  and then its not possible to know which zfs-release package to install ... so all reverts back to trial'n'error.

**Comment by x3nb63** [comment]
my brain came up with yet another way:

`VERSION_ID=$(rpm -q --queryformat '%{VERSION}' centos-linux-release)`

while the files managed by that package are useless / hard-to-parse the package itself knows what it is.

... can be enhanced to work for stream as well ...
...
