### ISSUE TITLE
Importing a pool with corrupted log device

### ISSUE THREAD

**Issue by RyanHow** [openzfs/zfs#2099]
If a log device is corrupted, zpool import will refuse to import the pool. The workaround is to remove the actual device from the system, then zpool import -m to import the pool with the missing device.

It would be great to be able to zpool import -f (Or some other flag like -m) and import the pool regardless of the corrupt log device. The pool could then just import in a degraded state (like when a device is missing).

It just appears to be a hole in the zpool import command. Although data corruption in the log device could result in lost data, the only thing that you can really do in this case is import the pool regardless and continue on with the lost data.

**Comment by durval-menezes** [comment]
Hello, 

Referring to the following, above: https://github.com/zfsonlinux/zfs/issues/2099#issuecomment-54532363, more specifically to that part: 

> Giving either as 'zpool remove git xxx' gives no error but doesn't change the pool." 

I'm having the exact same issue with one of my pools here, running ZoL's latest stable (0.6.5.3) installed from the official repo on EL6. The only difference is that, contrary to @dswartz, I tried to export the pool, remove the log device and then import it back in, but *still* the "zpool remove" accomplishes nothing and the device keeps showing on zpool status. I've posted extensively about the problem on a zfs-discuss mailing list thread starting here: http://list.zfsonlinux.org/pipermail/zfs-discuss/2015-December/024006.html

I'm going ahead and opening a new issue for this, referring to this one, and to the above mail thread.

Cheers,
Durval.

**Comment by ksalman** [comment]
I am also running into this - cannot remove an OFFLINE zil device. I am using version 0.6.5.6-0ubuntu14.


	NAME                                    STATE     READ WRITE CKSUM
	tank                                    DEGRADED     0     0     0
	  mirror-0                              ONLINE       0     0     0
	    sda                                 ONLINE       0     0     0
	    sdb                                 ONLINE       0     0     0
	  mirror-1                              ONLINE       0     0     0
	    sdc                                 ONLINE       0     0     0  (resilvering)
	    sdd                                 ONLINE       0     0     0
	logs
	  64712f3c-9b0a-11e6-a777-001b21709ddc  OFFLINE      0     0     0

**Comment by zeigerpuppy** [comment]
I am having a (real-life) problem importing a pool at the moment.
My log device corrupted due to a power outage and the pool will now not import even with the `missing` option.
Is there a way to force it to import, I've tried all the commands I can think of:

The closest I get is with:

```
zpool import -f -m -d /dev/disk/by-id/scsi-35000cca03e167XXX-part1
```
which returns

```
   pool: data
     id: 13736941278548912923
  state: UNAVAIL
 status: One or more devices are missing from the system.
 action: The pool cannot be imported. Attach the missing
	devices and try again.
   see: http://zfsonlinux.org/msg/ZFS-8000-6X
 config:

	data                                        UNAVAIL  missing device
	  raidz2-0                                  ONLINE
	    scsi-35000cca03e94cXXX                 ONLINE
	    scsi-35000cca03ea73XXX                  ONLINE
	    scsi-35000cca03eb11XXX                  ONLINE
	    scsi-35000cca03eb42XXX                 ONLINE
	    scsi-35000cca03e088XXX                  ONLINE
	    scsi-35000cca01adb1XXX                  ONLINE
	    scsi-35000cca03e167XXX                  ONLINE
	    scsi-35000cca03e172XXX                  ONLINE
	logs
	  ata-MK0200GCTYV_BTTV320101VFXXX-part6  UNAVAIL  corrupted data

	Additional devices are known to be part of this pool, though their
	exact configuration cannot be determined.
```

I also tried reformatting the log partition but that doesn't seem to help.
I guess there must be some way to offline the log, but can't seem to find a way to do it in a pool that won't import.

**Comment by behlendorf** [comment]
@zeigerpuppy you're absolutely on the right track, the `-m` option should have worked.  Can you try importing your pool again with the following command:

```
zpool import -f -m -d /dev/disk/by-id/ tank
```

Assuming that fails, please grab the kernel debug log by dumping `/proc/spl/kstat/zfs/dbgmsg`.  The lines of interest will be prefixed with `spa_load` so I'd recommend running something like:

```
grep spa_load /proc/spl/kstat/zfs/dbgmsg
```

This should give us a better indication of exactly what the issue is.

**Comment by zeigerpuppy** [comment]
Thanks for the tip.
As you predicted the pool fails to import, the messages from `/proc/spl/kstat/zfs/dbgmsg` are below:

```
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633752
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663794   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633752
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633751
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633751
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633750
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633750
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): some log devices are missing, ZIL is dropped.
1578663795   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: vdev_load failed [error=2]
1578663795   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664082   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664082   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664137   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664137   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664246   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664247   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633753
1578664247   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633752
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633752
1578664247   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633751
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664247   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633751
1578664248   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): spa_load_retry: rewind, max txg: 33633750
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): LOADING
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config untrusted): using uberblock with txg=33633750
1578664248   spa_misc.c:393:spa_load_failed(): spa_load(data, config trusted): FAILED: some log devices are missing
1578664248   spa_misc.c:408:spa_load_note(): spa_load(data, config trusted): UNLOADING
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578664260   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578664260   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578697883   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578697883   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
```

I have also included the output of zdb (sanitised serial numbers) for reference:

```
data:
    version: 5000
    name: 'data'
    state: 0
    txg: 33623486
    pool_guid: 13736941278548912923
    errata: 0
    hostid: 8323329
    hostname: 'ocelot'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 13736941278548912923
        children[0]:
            type: 'raidz'
            id: 0
            guid: 10302097311291941285
            nparity: 2
            metaslab_array: 34
            metaslab_shift: 37
            ashift: 12
            asize: 24004626743296
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 475
            children[0]:
                type: 'disk'
                id: 0
                guid: 6395614434348585949
                path: '/dev/disk/by-id/scsi-35000cca03e94cXXX-part1'
                whole_disk: 1
                DTL: 474
                create_txg: 4
                com.delphix:vdev_zap_leaf: 477
            children[1]:
                type: 'disk'
                id: 1
                guid: 13886622606314949005
                path: '/dev/disk/by-id/scsi-35000cca03ea73XXX-part1'
                whole_disk: 1
                DTL: 473
                create_txg: 4
                com.delphix:vdev_zap_leaf: 478
            children[2]:
                type: 'disk'
                id: 2
                guid: 15223255819206260964
                path: '/dev/disk/by-id/scsi-35000cca03eb11XXX-part1'
                whole_disk: 1
                DTL: 472
                create_txg: 4
                com.delphix:vdev_zap_leaf: 479
            children[3]:
                type: 'disk'
                id: 3
                guid: 13152668632038442322
                path: '/dev/disk/by-id/scsi-35000cca03eb42XXX-part1'
                whole_disk: 1
                DTL: 471
                create_txg: 4
                com.delphix:vdev_zap_leaf: 480
            children[4]:
                type: 'disk'
                id: 4
                guid: 10359585613055231207
                path: '/dev/disk/by-id/scsi-35000cca03e088XXX-part1'
                devid: 'scsi-35000cca03e088XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy5-lun-0'
                whole_disk: 1
                DTL: 488
                create_txg: 4
                com.delphix:vdev_zap_leaf: 487
            children[5]:
                type: 'disk'
                id: 5
                guid: 12665232198200720196
                path: '/dev/disk/by-id/scsi-35000cca01adb1XXX-part1'
                devid: 'scsi-35000cca01adb1XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy6-lun-0'
                whole_disk: 1
                DTL: 641
                create_txg: 4
                com.delphix:vdev_zap_leaf: 640
            children[6]:
                type: 'disk'
                id: 6
                guid: 10521707952703103872
                path: '/dev/disk/by-id/scsi-35000cca03e167XXX-part1'
                whole_disk: 1
                DTL: 69
                create_txg: 4
                com.delphix:vdev_zap_leaf: 483
            children[7]:
                type: 'disk'
                id: 7
                guid: 6315495063040771963
                path: '/dev/disk/by-id/scsi-35000cca03e172XXX-part1'
                devid: 'scsi-35000cca03e172XXX-part1'
                phys_path: 'pci-0000:03:00.0-sas-phy4-lun-0'
                whole_disk: 1
                DTL: 514
                create_txg: 4
                com.delphix:vdev_zap_leaf: 494
        children[1]:
            type: 'disk'
            id: 1
            guid: 8899809195679796448
            path: '/dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF20XXXX-part6'
            whole_disk: 0
            metaslab_array: 38
            metaslab_shift: 25
            ashift: 9
            asize: 5995233280
            is_log: 1
            DTL: 468
            create_txg: 27392809
            com.delphix:vdev_zap_leaf: 485
            com.delphix:vdev_zap_top: 486
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

The pool recently had two drives replaced and resilvered, which all went well.

**Comment by behlendorf** [comment]
Thus far I haven't been able to reproduce the issue locally, but there are a few more things I'd like to try.  In the meanwhile, would you mind checking if you can import the pool readonly.

```
zpool import -m -o readonly=on -d /dev/disk/by-id/ data
```

**Comment by zeigerpuppy** [comment]
unfortunately read-only doesn't seem to work either (same errors as before in `dbgmsg`.

```
zpool import -m -o readonly=on -d /dev/disk/by-id/scsi-35000cca03e167XXX-part1 data
```

outputs
```
cannot import 'data': no such pool or dataset
	Destroy and re-create the pool from
	a backup source.
```

**Comment by DurvalMenezes** [comment]
For the record, after keeping my bad pool around (see  #4067) for the best part of 3 years, a few months ago I migrated it to another machine/disk set and erased the previous one :-P so I can no longer help to debug this. 

Anyway, trying to reproduce the issue here with a testpool (creating a 2-disk mirror with a separate log device, then exporting, then first removing the log device from the system and trying to import the pool back, then ditto but purposefully corrupting the log device with `dd` while the pool was exported) failed: the pool failed to import normally (with the expected "The devices below are missing or corrupted, use '-m' to import the pool anyway") but then succeeding when using the '-m' option. FWIW, tests done with ZFS 0.8.2 manually compiled from source and installed on Ubuntu 18.04.

**Comment by zeigerpuppy** [comment]
I'm wondering if there is a brute-force way to export this pool and then reimport.
Ideally I'd like to recover the data that is on the 8 drives as it should be fine and is a lot faster than dumping back from backups.

Still stuck with trying to get the pool to load with the corrupted log device.
Any further suggestions heartily accepted!

**Comment by zeigerpuppy** [comment]
having a look at logs in more detail, I think I may be on to something:

```
1578902441   spa.c:5623:spa_tryimport(): spa_tryimport: importing data
1578902441   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): LOADING
1578902441   vdev.c:124:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/scsi-35000cca03ea73xxx-part1': best uberblock found for spa $import. txg 33633753
1578902441   spa_misc.c:408:spa_load_note(): spa_load($import, config untrusted): using uberblock with txg=33633753
1578902441   vdev.c:124:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6': vdev_validate: vdev label pool_guid doesn't match config (15977575221519336500 != 13736941278548912923)
1578902441   spa_misc.c:393:spa_load_failed(): spa_load($import, config trusted): FAILED: some log devices are missing
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():   vdev 0: root, guid: 13736941278548912923, path: N/A, degraded
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():     vdev 0: raidz, guid: 10302097311291941285, path: N/A, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 0: disk, guid: 6395614434348585949, path: /dev/disk/by-id/scsi-35000cca03e94cxxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 1: disk, guid: 13886622606314949005, path: /dev/disk/by-id/scsi-35000cca03ea73xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 2: disk, guid: 15223255819206260964, path: /dev/disk/by-id/scsi-35000cca03eb11xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 3: disk, guid: 13152668632038442322, path: /dev/disk/by-id/scsi-35000cca03eb42xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 4: disk, guid: 10359585613055231207, path: /dev/disk/by-id/scsi-35000cca03e088xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 5: disk, guid: 12665232198200720196, path: /dev/disk/by-id/scsi-35000cca01adb1xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 6: disk, guid: 10521707952703103872, path: /dev/disk/by-id/scsi-35000cca03e167xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():       vdev 7: disk, guid: 6315495063040771963, path: /dev/disk/by-id/scsi-35000cca03e172xxx-part1, healthy
1578902441   vdev.c:178:vdev_dbgmsg_print_tree():     vdev 1: disk (log), guid: 8899809195679796448, path: /dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6, can't open
1578902441   spa_misc.c:408:spa_load_note(): spa_load($import, config trusted): UNLOADING
```

note the line
```
1578902441   vdev.c:124:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6': vdev_validate: vdev label pool_guid doesn't match config (15977575221519336500 != 13736941278548912923)
```

I guess the guid has changed, so that may be causing the inability to use allow the missing device...

I will try looking for a way to set the guid.

**Comment by zeigerpuppy** [comment]
scrub that idea, I erased the label and it didn't help
```
zpool labelclear /dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6 -f
```

the error does change, as is to be expected:

```
1578903444   vdev.c:124:vdev_dbgmsg(): disk vdev '/dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6': vdev_validate: failed reading config for txg 33633753
...
1578903444   vdev.c:178:vdev_dbgmsg_print_tree():     vdev 1: disk (log), guid: 8899809195679796448, path: /dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VF200xxx-part6, can't open
```

**Comment by zeigerpuppy** [comment]
Additional: I noticed this command from the [Oracle docs](https://docs.oracle.com/cd/E88353_01/html/E72487/zpool-8.html), but it is not implemented in zfsonlinux:

```
zpool label [–d path ... | –c cachefile] –R <pool | id> [device]
```

>    This is an undo operation for the `zpool label -C` command. It recovers ZFS metadata for a specific pool and, if enough of the pool's devices are restored this way, makes it possible to reimport the pool. If a device is specified, it recovers metadata only on this device.

 >   A pool can be identified by its name or the numerical identifier. If the `–d` option is not specified, this command searches for devices in `/dev/dsk` directory. A device must be specified using its full path and name.

This would seem to allow recovering metadata from one device to another, is there any equivalent in zfsonlinux?

**Comment by behlendorf** [comment]
@zeigerpuppy I wasn't aware of the `zpool label` command from the Oracle docs.  That kind of functionality to potentially recreate a label could definitely be handy in some situations.  But I don't think it would be helpful in this particular case since we should be able to ignore that device entirely.

It's also surprising that a readonly import would fail.  When importing readonly the log device cannot be replayed so it's skipped in this circumstance.  Looking at the logs you posted it also appears that the import attempted to rewind several txgs to import.  This is expected for a power failure, it's not impossible that there is an issue in the import path when handling both failures.

Can you try importing the pool at a specific transaction group.  Based on your logs you'll want to try `33633752`, and it wouldn't hurt to try `33633751` if that fails.  You can run:

```
zpool import -T 33633752 -m -o readonly=on -d /dev/disk/by-id/ data
```

If you're willing to privately share the pool metadata for debugging purposes there is some additional investigation which could be done.  The `zdb` command can be used to dump a sparse copy of the pool.  This would make it possible for a developer to locally debug the issue since we've been unable to intentionally reproduce it.  The `zdb -x` copy can be used for this, from the man page:

```
     -x dumpdir
             All blocks accessed will be copied to files in the specified directory.  The
             blocks will be placed in sparse files whose name is the same as that of
             the file or device read.  zdb can be then run on the generated files.
             Note that the -bbc flags are sufficient to access (and thus copy) all
             metadata on the pool.
```

If you're game, you can generate the vdev dump like this:

```
mkdir /var/tmp/data-pool
zdb -e -p /dev/disk/by-id/ -bbc -x /var/tmp/data-pool data
```

**Comment by zeigerpuppy** [comment]
@behlendorf I tried both:

```
zpool import -T 33633752 -m -o readonly=on -d /dev/disk/by-id/ data
```
and

```
zpool import -T 33633751 -m -o readonly=on -d /dev/disk/by-id/ data
```

but they both return error:

```
cannot import 'data': one or more devices is currently unavailable
```

there's no new messages in `/proc/spl/kstat/zfs/dbgmsg`

I am happy to share the metadata, however, when I tried dumping the metadata with the commands:

```
mkdir /var/tmp/data-pool
zdb -e -p /dev/disk/by-id/ -bbc -x /var/tmp/data-pool data
```

I get error:

```
zdb: can't open 'data': File exists
```

there is a small `zpool.cache` file dumped in that dir (5196 bytes)

**Comment by OCDPro** [comment]
›I have this same issue due to power cuts.

The log ssd has been faulted 

![Screen Shot 2020-01-16 at 15 43 05](https://user-images.githubusercontent.com/59962912/72529942-fc651200-3876-11ea-82bf-10e633ed0ea8.png)

**Comment by OCDPro** [comment]
Resolved.

The import issue was solved by destroying the faulted log disk's file system completely. 
Removing it physically would also have worked but,  the log disk data was only corrupted because of a power failure during write operations and not a physical faulty disk, so removing it would have been a waste.
Forcing the faulted log in to a working pool ensured the corrupted disk file system was overwritten and was just as effective as what removing it would have been.

zpool add **working-pool-name** cache **disk-id-of-broken-zil**  -f  


Now that the corrupted disk was completely forced out of its old pool,  zpool  import was then able to import and bring the faulty pool back online by rolling back to the other 2 uncorrupted log disks  "See screenshot from my previous post".    

zpool import -fF -m **fautly-pool-name**


The lesson here is to mirror the log disks, although that might have given me 3 corrupted mirrors.  
I will need to do extensive tests on a test system later, ie, pull the plug while writing to a mirrored ZIL.   

To prevent this problem happening again on this live production pool, ZIL logs have been removed until further DR tests can be conducted.


Here is the now fully functional and healthy repaired pool
![Screen Shot 2020-01-18 at 14 00 18](https://user-images.githubusercontent.com/59962912/72663615-5859a300-39fd-11ea-8ba3-e14c360ae2d7.png)

**Comment by FransUrbo** [comment]
On 18 Jan 2020, at 12:25, OCDPro <notifications@github.com> wrote:

> The import issue was solved by destroying the faulted log disk's file system completely.

How did you do that? I thought you said you had ‘dd’ the device before trying to import the pool.. ?
> removing it would have been a waste.
> 
You could have removed the disk, imported the pool and then put the disk back. If you have
hot-swap bays that is…

A ‘eject’ command could also have been done. In the SCSI subsystem, you can easily remove
and attach a device from the command line by utilising the /sys FS..
> The lesson here is to mirror the log disks, although that might have given me 3 corrupted mirrors.
> 
Not necessarily.. The replication isn’t always instantaneous.. Or?

**Comment by OCDPro** [comment]
> On 18 Jan 2020, at 12:25, OCDPro ***@***.***> wrote: The import issue was solved by destroying the faulted log disk's file system completely.
> How did you do that? I thought you said you had ‘dd’ the device before trying to import the pool.. ?
No, that was someone else's issue in this thread where "dd" did not work.  I think @zeigerpuppy, who only has 1 log disk in the pool.
I joined this thread yesterday and I believe dd would also have also helped my situation.    
My system had 2 other clean log disks, so zpool import was able to roll back to uncorrupted logs.   Not sure if the import would have worked for me if the corrupted ZIL log was the only log disk though.     
The system I am working on had 3 un-mirrored logs with 1 log disk corruption.   So forcing the disk with corrupted logs in to another pool was one way to keep track of the disk-id and have active data written to it just to be sure.  This system has an excess of 80 spinning disks as well as 3 cache ssd's and 2 disk boot mirror ssd's with all 5 ssd's id's are almost identical.     

> removing it would have been a waste.
> You could have removed the disk, imported the pool and then put the disk back. If you have hot-swap bays that is… A ‘eject’ command could also have been done. In the SCSI subsystem, you can easily remove and attach a device from the command line by utilising the /sys FS..
Thank you, I will read up more on /sys FS.   The ssd's are not hot swap and the system is remote so anything that can save a drive to site is welcome advice :) 

> The lesson here is to mirror the log disks, although that might have given me 3 corrupted mirrors.
> Not necessarily.. The replication isn’t always instantaneous.. Or?
Agreed, not always instant replication.
I wonder if creating a ZIL config that uses a combination of mirrors in single V-Dev's.   Say 6 disks divided in to 3 separate 2 disk mirrors, then each pair added as a single logs separately to the pool as 3 single un-mirrored ZIL's.  3 ZIL's x 2 disk mirrors.

**Comment by zeigerpuppy** [comment]
@OCDPro I tried your idea of moving the corrupted log device to another pool:

```
zpool create test /dev/disk/by-id/ata-MK0200GCTYV_BTTV320101VFXXX-part6
```

As you suggested, this now changes the device from UNAVAIL to FAULTED in my `data` pool.

However, in my case, this still doesn't allow the importing of the faulty pool.

```
zpool import -fF -m data
```

returns 

```
cannot import 'data': no such pool or dataset
	Destroy and re-create the pool from
	a backup source.
```

and `zpool import` returns

```
   pool: data
     id: 13736941278548912923
  state: UNAVAIL
 status: One or more devices are missing from the system.
 action: The pool cannot be imported. Attach the missing
	devices and try again.
   see: http://zfsonlinux.org/msg/ZFS-8000-6X
 config:

	data                                        UNAVAIL  missing device
	  raidz2-0                                  ONLINE
	    scsi-35000cca03e94c830                  ONLINE
	    scsi-35000cca03ea735e0                  ONLINE
	    scsi-35000cca03eb112c0                  ONLINE
	    scsi-35000cca03eb42f00                  ONLINE
	    scsi-35000cca03e088054                  ONLINE
	    scsi-35000cca01adb1964                  ONLINE
	    scsi-35000cca03e167738                  ONLINE
	    scsi-35000cca03e1724f4                  ONLINE
	logs
	  ata-MK0200GCTYV_BTTV320101VF200GGN-part6  FAULTED  corrupted data

	Additional devices are known to be part of this pool, though their
	exact configuration cannot be determined.
```

**Comment by OCDPro** [comment]
@zeigerpuppy 

Have you tried completely deleting the partition  ......FXXX-part6 with fdisk or cfdisk? So that there is no longer a "part6"

This should make the faulted log disk go missing to the zfs pool,  then try import again 

zpool import -f -F -m poolname

Not sure if this will work without a secondary log device to roll back to.

**Comment by zeigerpuppy** [comment]
Thanks for the suggestion @OCDPro.
I eventually accepted the fate of the array being unrecoverable and have reinitialised the drives.
Not a big loss, as it was a backup server, but needed to get those drives back in service.

**Comment by wiesl** [comment]
Does a
wipefs --all --force /dev/ata-MK0200GCTYV_BTTV320101VF200GGN-part6
or something like this help?
